import {
    Button,
    HorizontalBox,
    Spinner,
    StandardListView,
    VerticalBox
} from "std-widgets.slint";

export component MainWindow inherits Window {
    title: "PsyLink";
    icon: @image-url("icon.svg");
    preferred-width: 400pt;
    preferred-height: 500pt;

    HorizontalBox {
        alignment: center;
        VerticalBox {
            alignment: center;
            spacing: 20pt;
            Spinner {
                indeterminate: true;
            }
            Text {
                horizontal-alignment: center;
                text: "Scanning for nearby PsyLink devices...\n\nPlease make sure that your PsyLink is turned on and the battery charged.";
            }
        }
    }
}
